### ISSUE TITLE
[Spec]: Expose Account UUID

### ISSUE THREAD

**Issue by refs** [owncloud/ocis-proxy#35]
### Gathered Requirements

- having UUID on every request on the proxy
- user object upon authentication (phoenix).
- make js generated from swagger do requests through the proxy instead of the service.

### Formal Requirements

Phoenix has no knowledge of which **Ocis Account** the **authenticated** user has on the `ocis-accounts` service. A design proposal is to render the Ocis Account UUID on every request that goes through the proxy. This should allow extensions to request its configuration values from the **[Settings Service](github.com/owncloud/ocis-settings/)** based on the account `uuid`.

I identify changes in the following services:

- Ocis Proxy
  - need to know where the **Ocis Accounts** service is running.
- Ocis Accounts
  - [query message](https://github.com/owncloud/ocis-accounts/blob/feature/settings/pkg/proto/v0/accounts.proto#L66-L68) needs to be more flexible. `key` alone is not enough to query for an account. Adding some of the user claims could be used for querying the account files.
- We need the middleware for adding the account uuid of the authenticated user to **every** request. That could be used for **validation** mechanisms when the authenticated user is impersonating another user (i.e. checking through roles & permissions, if the authenticated user is allowed to impersonate the other user). (Impersonation as in e.g. `retrieve settings values for another user`, not talking about full frontend impersonation)
- Extensions will do a first call to the `ocis-accounts`

This flow can be achieved with a middleware in the Proxy. With this UUID an extension can then request its settings to the settings service through the proxy.

### How do we want to consume the UUID

- Response header
- Response [payload](https://github.com/owncloud/ocis-accounts/blob/feature/settings/pkg/proto/v0/accounts.proto#L18-L20)

### [Ubiquitous Language](https://martinfowler.com/bliki/UbiquitousLanguage.html)

- **Ocis Accounts**: refers to github.com/owncloud/ocis-accounts
- **Account UUID**: refers to the [account's UUID](https://github.com/owncloud/ocis-accounts/blob/feature/settings/pkg/proto/v0/accounts.proto#L23). This UUID only exists in the account service.

### Links of Interest

- [Request Flow \| ownCloud](https://owncloud.github.io/ocis/request-flow/)

**Comment by refs** [comment]
Perhaps @butonic would like to add some comments. I just came with this spec, it probably has some blind spots we should catch at the spec level before jumping to the implementation.

**Comment by butonic** [comment]
the account_uuid middleware now mints a token that includes the uuid that was generated by the accounts service. @refs and @kulmann I think that covers this issue?

**Comment by refs** [comment]
@butonic it does! 🙆‍♂️
