### ISSUE TITLE
Unknown internal server error

### ISSUE THREAD

**Issue by refs** [owncloud/ocis-proxy#68]
I'm getting an unknown internal server error with no logs

Steps to reproduce:

1. checkout master on this repo
2. checkout to owncloud/ocis -> master
  2.1 `replace github.com/owncloud/ocis-proxy => ../ocis-proxy` (your local proxy)
3. `go run cmd/ocis/main.go server`
4. on the browser: `https://localhost:9200`

expected: see login screen
got: internal server error

**Comment by refs** [comment]
while bisecting, checking out on this commit: `9cdff8c8b75f9c6c36ab4266990107efe4480454` by doing:

`git checkout 9cdff8c` this bug does not occur. Evidences point to https://github.com/owncloud/ocis-proxy/pull/66

**Comment by kulmann** [comment]
Same on my machine.

**Comment by refs** [comment]
managed to trace it down to this line:

```golang
tokenManager, err := jwt.New(map[string]interface{}{
	"secret": opt.TokenManagerConfig.JWTSecret,
})
```

on this file: https://github.com/owncloud/ocis-proxy/blob/master/pkg/middleware/create_home.go#L24-L26, this is throwing an error.

**Comment by refs** [comment]
Upon inspecting the error we get this:

`2020-07-13T14:53:02+02:00 ERR error creating a token manager error="jwt: secret for signing payloads is not defined in config" service=proxy`

**Comment by IljaN** [comment]
@refs Close?

**Comment by refs** [comment]
wat the PR didn't close the issue. weird.
